image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
  - build

build:
  stage: build
  script:
    - >
      docker build
      -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-$NAME"
      -f ./Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-$NAME"
  tags:
    - docker
  only:
    - tags
  when: manual
